import React, { useState } from 'react';
import { FormArtifact, FormQuestion } from '../../types/orchestrator';
import {
  ClipboardList,
  Plus,
  ExternalLink,
  Sparkles,
  Table,
  CheckCircle2,
  HelpCircle,
  Users,
  Clock,
  ArrowRight,
} from 'lucide-react';
import { executeAgentTask } from '../../services/api';

interface FormsWorkspaceProps {
  forms: FormArtifact[];
  onAddForm: (form: FormArtifact) => void;
  onStreamToSheets: (form: FormArtifact) => void;
}

export const FormsWorkspace: React.FC<FormsWorkspaceProps> = ({
  forms,
  onAddForm,
  onStreamToSheets,
}) => {
  const [selectedFormId, setSelectedFormId] = useState<string>(forms[0]?.id || '');
  const [isGenerating, setIsGenerating] = useState(false);
  const [showConfirmModal, setShowConfirmModal] = useState(false);
  const [newTitle, setNewTitle] = useState('');
  const [newDesc, setNewDesc] = useState('');

  const selectedForm = forms.find((f) => f.id === selectedFormId) || forms[0];

  const handleConfirmCreateForm = async () => {
    if (!newTitle.trim()) return;
    setIsGenerating(true);

    const newForm: FormArtifact = {
      id: `form-${Date.now()}`,
      title: newTitle,
      description: newDesc || 'Generated by Google Forms Agent for client requirements intake.',
      formUrl: `https://docs.google.com/forms/d/${Date.now()}/viewform`,
      responseCount: 0,
      linkedSheetName: 'Q4_Content_Automation_Matrix.gsheet',
      lastResponseAt: 'Just now',
      questions: [
        {
          id: 'q-1',
          title: 'What is your primary use case for Google Agent swarms?',
          type: 'CHOICE',
          options: ['Email & Calendar Scheduling', 'Content & Presentation Pipeline', 'Drive Asset Cataloging', 'Ad Campaign Management'],
          required: true,
        },
        {
          id: 'q-2',
          title: 'Describe any specific compliance or OAuth approval requirements:',
          type: 'PARAGRAPH',
          required: false,
        },
      ],
    };

    onAddForm(newForm);
    setSelectedFormId(newForm.id);

    // Run agent execution
    await executeAgentTask(
      'forms',
      `Create and structure new Google Form: "${newTitle}"`,
      { form: newForm }
    );

    setIsGenerating(false);
    setShowConfirmModal(false);
    setNewTitle('');
    setNewDesc('');
  };

  return (
    <div className="bg-slate-900/90 rounded-2xl border border-slate-800 p-6 flex flex-col gap-6 shadow-xl">
      {/* Workspace Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-800 pb-4">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-violet-600/10 border border-violet-500/30 flex items-center justify-center text-violet-400">
            <ClipboardList className="w-5 h-5 text-violet-400" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h2 className="text-lg font-semibold text-slate-100 tracking-tight">
                Google Forms Agent Workspace
              </h2>
              <span className="text-xs text-slate-400">· Google Forms API</span>
            </div>
            <p className="text-xs text-slate-400">
              Autonomous survey schema design, client intake questionnaire generation, and live Sheets routing
            </p>
          </div>
        </div>

        <button
          onClick={() => setShowConfirmModal(true)}
          className="flex items-center gap-2 bg-violet-600 hover:bg-violet-500 text-white text-xs font-semibold px-4 py-2 rounded-xl transition-all shadow-md active:scale-95"
        >
          <Sparkles className="w-3.5 h-3.5" />
          <span>New Google Form</span>
        </button>
      </div>

      {/* Forms Main Content */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
        {/* Form Selector List */}
        <div className="space-y-2 border-r border-slate-800/80 pr-3">
          <div className="text-xs font-semibold uppercase tracking-wider text-slate-400 mb-2">
            Active Google Forms ({forms.length})
          </div>

          {forms.map((form) => {
            const isSelected = form.id === selectedForm?.id;
            return (
              <div
                key={form.id}
                onClick={() => setSelectedFormId(form.id)}
                className={`p-3.5 rounded-xl border cursor-pointer transition-all duration-150 ${
                  isSelected
                    ? 'bg-violet-950/40 border-violet-500/60 shadow-sm'
                    : 'bg-slate-950/50 border-slate-800/80 hover:border-slate-700'
                }`}
              >
                <div className="flex items-center justify-between text-[11px] text-slate-400 mb-1">
                  <span className="font-mono text-emerald-400 font-medium flex items-center gap-1">
                    <Users className="w-3 h-3" />
                    <span>{form.responseCount} Responses</span>
                  </span>
                  <span className="font-mono text-[10px]">{form.lastResponseAt}</span>
                </div>
                <div className="text-xs font-semibold text-slate-100 truncate mb-1">
                  {form.title}
                </div>
                <div className="text-[11px] text-slate-400 line-clamp-1">
                  {form.description}
                </div>
              </div>
            );
          })}
        </div>

        {/* Selected Form Detail View */}
        {selectedForm ? (
          <div className="md:col-span-2 flex flex-col justify-between bg-slate-950/60 rounded-xl border border-slate-800 p-5 space-y-5">
            <div>
              {/* Form Info Header */}
              <div className="border-b border-slate-800 pb-4">
                <div className="flex items-start justify-between gap-3 mb-2">
                  <h3 className="text-base font-semibold text-slate-100">
                    {selectedForm.title}
                  </h3>
                  <a
                    href={selectedForm.formUrl}
                    target="_blank"
                    rel="noreferrer"
                    className="flex items-center gap-1 text-xs text-blue-400 hover:text-blue-300 transition-colors shrink-0"
                  >
                    <span>View Form</span>
                    <ExternalLink className="w-3.5 h-3.5" />
                  </a>
                </div>
                <p className="text-xs text-slate-300 leading-relaxed mb-3">
                  {selectedForm.description}
                </p>

                <div className="flex flex-wrap items-center gap-3 text-xs text-slate-400">
                  <span className="flex items-center gap-1 text-emerald-400 font-mono">
                    <Users className="w-3.5 h-3.5" />
                    <span>{selectedForm.responseCount} Submissions</span>
                  </span>
                  <span aria-hidden="true" className="text-slate-600">·</span>
                  <span className="flex items-center gap-1 text-slate-300">
                    <Table className="w-3.5 h-3.5 text-emerald-400" />
                    <span>Routing to: {selectedForm.linkedSheetName}</span>
                  </span>
                </div>
              </div>

              {/* Form Schema Questions */}
              <div className="space-y-4 pt-4">
                <div className="text-xs font-semibold uppercase tracking-wider text-slate-400">
                  Form Question Schema ({selectedForm.questions.length} Items)
                </div>

                <div className="space-y-3">
                  {selectedForm.questions.map((q, idx) => (
                    <div
                      key={q.id}
                      className="p-4 bg-slate-900/80 rounded-xl border border-slate-800/80 space-y-2"
                    >
                      <div className="flex items-center justify-between text-xs">
                        <span className="font-semibold text-slate-200">
                          {idx + 1}. {q.title}
                        </span>
                        <span className="font-mono text-[10px] text-slate-500 uppercase">
                          {q.type} {q.required ? '· Required' : ''}
                        </span>
                      </div>

                      {q.options && (
                        <div className="space-y-1 pl-4 pt-1">
                          {q.options.map((opt, i) => (
                            <div key={i} className="flex items-center gap-2 text-xs text-slate-400">
                              <span className="w-1.5 h-1.5 rounded-full bg-slate-600" />
                              <span>{opt}</span>
                            </div>
                          ))}
                        </div>
                      )}
                    </div>
                  ))}
                </div>
              </div>
            </div>

            {/* Stream to Sheets CTA */}
            <div className="bg-slate-900 border border-slate-800 p-4 rounded-xl flex flex-col sm:flex-row sm:items-center justify-between gap-3 mt-6">
              <div className="text-xs text-slate-300">
                Incoming form responses are mapped directly into your Google Sheets tracking rows.
              </div>
              <button
                onClick={() => onStreamToSheets(selectedForm)}
                className="flex items-center gap-1.5 bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-semibold px-4 py-2 rounded-lg transition-colors shadow-sm shrink-0"
              >
                <Table className="w-3.5 h-3.5" />
                <span>Stream to Sheets Agent</span>
              </button>
            </div>
          </div>
        ) : (
          <div className="md:col-span-2 flex items-center justify-center p-12 text-xs text-slate-400">
            Select a form to inspect questions and response routing.
          </div>
        )}
      </div>

      {/* User Confirmation Dialog for Creating Form */}
      {showConfirmModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-sm animate-in fade-in duration-150">
          <div className="bg-slate-900 border border-slate-700 rounded-2xl w-full max-w-md p-6 space-y-4 shadow-2xl">
            <div className="flex items-center gap-3 text-slate-100 font-semibold text-sm">
              <ClipboardList className="w-5 h-5 text-violet-400" />
              <span>Create New Google Form</span>
            </div>

            <p className="text-xs text-slate-300">
              The Google Forms Agent will create this questionnaire schema and link responses to your Google Sheets tracker.
            </p>

            <div className="space-y-3">
              <div>
                <label className="text-[11px] uppercase tracking-wider text-slate-400 font-medium block mb-1">
                  Form Title
                </label>
                <input
                  type="text"
                  placeholder="e.g. Enterprise Automation Architecture Intake..."
                  value={newTitle}
                  onChange={(e) => setNewTitle(e.target.value)}
                  className="w-full bg-slate-950 border border-slate-700 rounded-xl px-3 py-2 text-xs text-slate-100 focus:outline-none focus:border-violet-500"
                />
              </div>

              <div>
                <label className="text-[11px] uppercase tracking-wider text-slate-400 font-medium block mb-1">
                  Description / Purpose
                </label>
                <textarea
                  rows={2}
                  placeholder="Explain what information this form collects..."
                  value={newDesc}
                  onChange={(e) => setNewDesc(e.target.value)}
                  className="w-full bg-slate-950 border border-slate-700 rounded-xl px-3 py-2 text-xs text-slate-100 focus:outline-none focus:border-violet-500 resize-none"
                />
              </div>
            </div>

            <div className="flex items-center justify-end gap-2 pt-3 border-t border-slate-800">
              <button
                onClick={() => setShowConfirmModal(false)}
                className="px-4 py-2 text-xs text-slate-400 hover:text-slate-200 transition-colors"
              >
                Cancel
              </button>
              <button
                disabled={!newTitle.trim() || isGenerating}
                onClick={handleConfirmCreateForm}
                className="flex items-center gap-2 bg-violet-600 hover:bg-violet-500 disabled:opacity-50 text-white text-xs font-semibold px-4 py-2 rounded-xl shadow-md transition-all active:scale-95"
              >
                {isGenerating ? 'Structuring Form...' : 'Confirm & Create'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
